# Generated by Django 4.2.5 on 2023-10-01 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='descripcion',
            field=models.TextField(max_length=100),
        ),
    ]
